/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InstitutesRouteImport } from './routes/institutes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InstitutesIndexRouteImport } from './routes/institutes.index'
import { Route as InstitutesNursingRouteImport } from './routes/institutes.nursing'
import { Route as InstitutesParamedicalRouteImport } from './routes/institutes.paramedical'
import { Route as InstitutesPuRouteImport } from './routes/institutes.pu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutesRoute = InstitutesRouteImport.update({
  id: '/institutes',
  path: '/institutes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutesIndexRoute = InstitutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutesRoute,
} as any)
const InstitutesNursingRoute = InstitutesNursingRouteImport.update({
  id: '/nursing',
  path: '/nursing',
  getParentRoute: () => InstitutesRoute,
} as any)
const InstitutesParamedicalRoute = InstitutesParamedicalRouteImport.update({
  id: '/paramedical',
  path: '/paramedical',
  getParentRoute: () => InstitutesRoute,
} as any)
const InstitutesPuRoute = InstitutesPuRouteImport.update({
  id: '/pu',
  path: '/pu',
  getParentRoute: () => InstitutesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/campus': typeof CampusRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/institutes': typeof InstitutesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/institutes/nursing': typeof InstitutesNursingRoute
  '/institutes/paramedical': typeof InstitutesParamedicalRoute
  '/institutes/pu': typeof InstitutesPuRoute
  '/institutes/': typeof InstitutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/campus': typeof CampusRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/institutes/nursing': typeof InstitutesNursingRoute
  '/institutes/paramedical': typeof InstitutesParamedicalRoute
  '/institutes/pu': typeof InstitutesPuRoute
  '/institutes': typeof InstitutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/campus': typeof CampusRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/institutes': typeof InstitutesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/institutes/nursing': typeof InstitutesNursingRoute
  '/institutes/paramedical': typeof InstitutesParamedicalRoute
  '/institutes/pu': typeof InstitutesPuRoute
  '/institutes/': typeof InstitutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application'
    | '/campus'
    | '/contact'
    | '/gallery'
    | '/institutes'
    | '/sitemap.xml'
    | '/institutes/nursing'
    | '/institutes/paramedical'
    | '/institutes/pu'
    | '/institutes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application'
    | '/campus'
    | '/contact'
    | '/gallery'
    | '/sitemap.xml'
    | '/institutes/nursing'
    | '/institutes/paramedical'
    | '/institutes/pu'
    | '/institutes'
  id:
    | '__root__'
    | '/'
    | '/application'
    | '/campus'
    | '/contact'
    | '/gallery'
    | '/institutes'
    | '/sitemap.xml'
    | '/institutes/nursing'
    | '/institutes/paramedical'
    | '/institutes/pu'
    | '/institutes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationRoute: typeof ApplicationRoute
  CampusRoute: typeof CampusRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  InstitutesRoute: typeof InstitutesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutes': {
      id: '/institutes'
      path: '/institutes'
      fullPath: '/institutes'
      preLoaderRoute: typeof InstitutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutes/': {
      id: '/institutes/'
      path: '/'
      fullPath: '/institutes/'
      preLoaderRoute: typeof InstitutesIndexRouteImport
      parentRoute: typeof InstitutesRoute
    }
    '/institutes/nursing': {
      id: '/institutes/nursing'
      path: '/nursing'
      fullPath: '/institutes/nursing'
      preLoaderRoute: typeof InstitutesNursingRouteImport
      parentRoute: typeof InstitutesRoute
    }
    '/institutes/paramedical': {
      id: '/institutes/paramedical'
      path: '/paramedical'
      fullPath: '/institutes/paramedical'
      preLoaderRoute: typeof InstitutesParamedicalRouteImport
      parentRoute: typeof InstitutesRoute
    }
    '/institutes/pu': {
      id: '/institutes/pu'
      path: '/pu'
      fullPath: '/institutes/pu'
      preLoaderRoute: typeof InstitutesPuRouteImport
      parentRoute: typeof InstitutesRoute
    }
  }
}

interface InstitutesRouteChildren {
  InstitutesNursingRoute: typeof InstitutesNursingRoute
  InstitutesParamedicalRoute: typeof InstitutesParamedicalRoute
  InstitutesPuRoute: typeof InstitutesPuRoute
  InstitutesIndexRoute: typeof InstitutesIndexRoute
}

const InstitutesRouteChildren: InstitutesRouteChildren = {
  InstitutesNursingRoute: InstitutesNursingRoute,
  InstitutesParamedicalRoute: InstitutesParamedicalRoute,
  InstitutesPuRoute: InstitutesPuRoute,
  InstitutesIndexRoute: InstitutesIndexRoute,
}

const InstitutesRouteWithChildren = InstitutesRoute._addFileChildren(
  InstitutesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationRoute: ApplicationRoute,
  CampusRoute: CampusRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  InstitutesRoute: InstitutesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
